dependencies: []

tasks:
  graspi_build:
    - graspi_js_copy
    - graspi_js_concat

options:
  basePath: 'bower_components/json2'
  destPath: 'tmp/graspi/build/json2'
  js:
    destFile: 'json2.js'
    files:
      - 'json2.js'