dependencies:
  - jquery-2.1.4
  - underscore-1.8.3
  - backbone.babysitter-0.1.8
  - backbone.wreqr-1.3.3

tasks:
  graspi_build:
    - graspi_js_copy
    - graspi_js_concat

options:
  basePath: 'bower_components/marionette/lib'
  destPath: 'tmp/graspi/build/marionette'
  js:
    destFile: 'marionette.js'
    files:
      - 'backbone.marionette.js'